version: '3.1'
services:
  stats-server:
    build: ./server
    image: ewm/server
    container_name: ewm-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats
      - spring_datasource_username=test
      - spring_datasource_password=test

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6540:5432"
    volumes:
      - dbewmstats:/var/lib/postgresql/data/
    environment:
#      - POSTGRES_PORT=5433
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./service
    image: ewm/service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
#      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdata
      - spring_datasource_username=test
      - spring_datasource_password=test

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5430"
    volumes:
      - dbewmdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
#      - POSTGRES_PORT=5430

volumes:
  dbewmstats:
  dbewmdata:
