version: '3.1'
services:
  stats-server:
    build: ./server
    image: ewm/server
    container_name: ewm-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=ewmstats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6540:5432"
    volumes:
      - dbewmstats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./service
    image: ewm/service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
#      - stats-server
    environment:
      - STATS_SERVER_URL=http://ewm-server:9090
      - DB_NAME=ewmdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    volumes:
      - dbewmdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  dbewmstats:
  dbewmdata:
